name: myvariable workflow
on: workflow_dispatch
env: 
 day_of_week: monday
jobs:
 greeting_job:
  runs-on: ubuntu-latest
  env:
   month: october
  steps:
   - name: print some statement for me for env testing 
     run: echo "my week is  $day_of_week and month is $month"
     env: 
      day_of_week: friday
   - name: fetcht the context of workflow 
     env:
        Job_CONTEXT: ${{ toJson(job) }}
     run: echo "$Job_CONTEXT"  
   - name: fetcht the context of workflow 
     env:
        strategy_CONTEXT: ${{ toJson(strategy) }}
     run: echo "$strategy_CONTEXT" 
   - name: fetcht the context of workflow 
     env:
        matrix_CONTEXT: ${{ toJson(matrix) }}
     run: echo "strategy_CONTEXT"     