name: myvariable workflow
on: workflow_dispatch
env: 
 day_of_week: monday
jobs:
 greeting_job:
  runs-on: ubuntu-latest
  env:
   month: october
  steps:
   - name: print some statement for me for env testing 
     run: echo "my week is  $day_of_week and month is $month"
     